#!/usr/bin/env bash

# Exit if any command fails, if any undefined variable is used, or if a pipeline fails
set -euo pipefail

# Check if the configuration file exists, and if it does, source it
if [ -f "$HOME/scripts/dmenu/config/config" ]; then
  . "$HOME/scripts/dmenu/config/config"
else
  echo "configuration file not found" && exit 1
fi

# Get selected process and confirm killing it.
selected=$(ps --user "$USER" -F | ${DMENU} "Search for process to kill:" "$@" | awk '{print $2" "$11}')
[[ -z "$selected" ]] && exit 1
answer=$(echo -e "No\nYes" | ${DMENU} "Kill $selected?" "$@")
[[ "$answer" == "Yes" ]] && kill -9 "${selected%% *}" && echo "Process $selected has been killed." && exit 0
echo "Program terminated." && exit 1

