#!/usr/bin/env bash

# Exit if any command fails, if any undefined variable is used, or if a pipeline fails
set -euo pipefail

. "$HOME/scripts/_menu-helper.sh" || exit 1

# Get selected process and confirm killing it.
selected=$(ps --user "$USER" -F | ${LAUNCHER} "Search for process to kill:" "$@" | awk '{print $2" "$11}')
[[ -z "$selected" ]] && exit 1
answer=$(echo -e "No\nYes" | ${LAUNCHER} "Kill $selected?" "$@")
[[ "$answer" == "Yes" ]] && kill -9 "${selected%% *}" && echo "Process $selected has been killed." && exit 0
echo "Program terminated." && exit 1

