#!/bin/bash

function send_notification() {
	volume=$(amixer get Master |grep % |awk '{print $5}'|sed -e 's/\[//' -e 's/\]//' | head -n 1)
	dunstify -a "Volume" -u low -r "9993" -h int:value:"$volume" -i "volume-$1" "Volume: ${volume}" -t 2000
}

case $1 in
up)
	# Set the volume on (if it was muted)
	amixer set Master 5%+ unmute
	send_notification $1
	;;
down)
	amixer set Master 5%- unmute
	send_notification $1
	;;
mute)
	amixer set Master toggle
	if $(amixer get Master |grep "off" |awk '{print $5}'|sed -e 's/\[//' -e 's/\]//' | head -n 1); then
		dunstify -i volume-mute -a "volume" -t 2000 -r 9993 -u low "Muted"
	else
		send_notification up
	fi
	;;
esac
