#!/bin/env bash
set -euo pipefail
source $HOME/.config/dmscripts/config

options=(
 "new pseint file"
 "quit")

 choice=$(printf '%s\n' "${options[@]}" | $DMENU 'Pseint file:')
 
 if [ "$choice" == "New pseint file" ]; then
  pseint=$(echo "" | $DMENU 'Enter new script:' "$@")
  name="$pseint"
  file=$HOME/Documents/pseint/$name.psc
if [ -d "$HOME/Documents/pseint" ]; then
  if [ -e "$HOME/Documents/pseint/$name.psc" ]; then
    $DMEDITOR "$file"
  else
    pseint -e  "$file"
  fi
fi

else
 echo "Program terminated." && exit 0
fi
