#!/bin/bash
# Simple script to generate a script file in my scripts directory
# set -euo pipefail
# DMENU="dmenu -i -l 20 -p"
# DMEDITOR="emacsclient -c -a emacs"
# # DMEDITOR="nvim"
#

set -euo pipefail
_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
if [[  -f "${_path}/_dm-helper.sh" ]]; then
  # shellcheck disable=SC1090,SC1091
  source "${_path}/_dm-helper.sh"
else
  # shellcheck disable=SC1090
  echo "No helper-script found"
fi

# script will not hit this if there is no config-file to load
# shellcheck disable=SC1090
source "$(get_config)"


options=(
  "New script"
  "quit"
)
  choice=$(printf '%s\n' "${options[@]}" | $DMENU 'Mkscripts:')

  if [ "$choice" == "New script" ]; then
  script_new=$(echo "" | $DMENU 'Enter new script:' "$@")
  name="$script_new"
  echo $name
  file=$HOME/.scripts/$name
if [ -d "$HOME/.scripts" ]; then
  if [ -e "$HOME/.scripts/$name" ]; then
    $DMEDITOR "$file"
  else
    echo "#!/bin/bash" >> "$file"
    chmod +x "$file"
    $DMEDITOR "$file"
  fi
fi

else
 echo "Program terminated." && exit 0
fi
