#!/bin/bash
set -euo pipefail
_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
if [[  -f "${_path}/_dm-helper.sh" ]]; then
  # shellcheck disable=SC1090,SC1091
  source "${_path}/_dm-helper.sh"
else
  # shellcheck disable=SC1090
  echo "No helper-script found"
fi

# script will not hit this if there is no config-file to load
# shellcheck disable=SC1090
source "$(get_config)"

options=(
 "laptop"
 "tv"
 "quit")

choice=$(printf '%s\n' "${options[@]}" | $DMENU 'Monitor Configuration:')

if [ "$choice" == "laptop" ]; then
 pacmd set-card-profile alsa_card.pci-0000_00_1b.0 output:analog-stereo+input:analog-stereo
 xrandr --output LVDS1 --primary --mode 1366x768 --pos 0x0 --rotate normal --output DP1 --off --output HDMI1 --off --output VGA1 --off --output VIRTUAL1 --off

fi

if [ "$choice" == "tv" ]; then
pacmd set-card-profile alsa_card.pci-0000_00_1b.0 output:hdmi-surround71
xrandr --output LVDS1 --off --output DP1 --off --output HDMI1 --mode 1360x768 --pos 0x0 --rotate normal --output VGA1 --off --output VIRTUAL1 --off
fi

if [ "$choice" == "quit" ]; then
    echo "Program terminated." && exit 0
fi
