#!/usr/bin/env bash
# shellcheck disable=SC2034
# Defined variables, modify anything in quotes to your preferred software
# LAUNCHER="rofi -dmenu -i -p"
# LAUNCHER="fzf --border=rounded --margin=5% --color=dark --height 100% --reverse --header=$(basename "$0") --info=hidden --header-first --prompt"
LAUNCHER="dmenu -i -p"
# LAUNCHER="wofi -dmenu -i -p"
WEB_BROWSER="qutebrowser"
TERMINAL_EMULATOR="alacritty -e"
TEXT_EDITOR="emacsclient -c -a emacs"
# TEXT_EDITOR="${TERMINAL_EMULATOR} nvim"
PDF_VIEWER="zathura"
LOGOUT_LOCKER="slock"

# setbg
setbg_dir="${HOME}/Pictures/wallpapers"
use_imv=0

# maim
maim_dir="${HOME}/Pictures/screenshots"
maim_file_prefix="maim"

# config list
declare -A confedit_list
confedit_list[confedit]="$HOME/scripts/config/config"
confedit_list[alacritty]="$HOME/.config/alacritty/alacritty.yml"
confedit_list[bash]="$HOME/.bashrc"
confedit_list[bash_profile]="$HOME/.bash_profile"
confedit_list[redshift]="$HOME/.config/redshift/redshift.conf"
confedit_list[neofetch]="$HOME/.config/neofetch/config.conf"
confedit_list[emacs]="$HOME/.config/emacs/config.org"
confedit_list[dunst]="$HOME/.config/dunst/dunstrc"
confedit_list[bat]="$HOME/.config/bat/config"
confedit_list[fish]="$HOME/.config/fish/config.fish"
confedit_list[picom]="$HOME/.config/picom/picom.conf"
confedit_list[ssh]="$HOME/.ssh/config"
confedit_list[xinitrc]="$HOME/.config/X11/xinitrc"
confedit_list[xresources]="$HOME/.config/X11/xresources"
confedit_list[nano]="$HOME/.config/nano/nanorc"
confedit_list[tmux]="$HOME/.config/tmux/tmux.conf"
confedit_list[zathura]="$HOME/.config/zathura/zathurarc"
confedit_list[starship]="$HOME/.config/starship/starship.toml"
confedit_list[zsh]="$HOME/.config/zsh/.zshrc"
confedit_list[zsh profile]="$HOME/.config/zsh/.zprofile"
confedit_list[zshenv]="$HOME/.zshenv"
confedit_list[aliases]="$HOME/.config/shell/aliases"
confedit_list[function]="$HOME/.config/shell/function"
confedit_list[lf]="$HOME/.config/lf/lfrc"
confedit_list[lf mappings]="$HOME/.config/lf/mappings"
confedit_list[lf settings]="$HOME/.config/lf/settings"
confedit_list[lf commands]="$HOME/.config/lf/commands"
confedit_list[autostart]="$HOME/.local/share/sweetdwm/autostart.sh"

# Radio list
declare -A radio_stations
radio_stations[50s Rewind]="https://zeno.fm/radio/50s-rewind/"
radio_stations[60s Rewind]="https://zeno.fm/radio/60s-rewind/"
radio_stations[70s Rewind]="https://zeno.fm/radio/70s-rewind/"
radio_stations[80s Rewind]="https://zeno.fm/radio/80s-rewind/"
radio_stations[90s Rock]="https://zeno.fm/radio/90s-rock/"
radio_stations[The 2000s]="https://zeno.fm/radio/the-2000s/"
radio_stations[Classical Radio]="https://zeno.fm/radio/classical-radio/"
radio_stations[Classical Relaxation]="https://zeno.fm/radio/radio-christmas-non-stop-classical/"
radio_stations[Classic Rock]="https://zeno.fm/radio/classic-rockdnb2sav8qs8uv/"
radio_stations[Gangsta49]="https://zeno.fm/radio/gangsta49/"
radio_stations[HipHop49]="https://zeno.fm/radio/hiphop49/"
radio_stations[Madhouse Country Radio]="https://zeno.fm/radio/madhouse-country-radio/"
radio_stations[PopMusic]="https://zeno.fm/radio/popmusic74vyurvmug0uv/"
radio_stations[PopStars]="https://zeno.fm/radio/popstars/"
radio_stations[RadioMetal]="https://zeno.fm/radio/radio-metal/"
radio_stations[RocknRoll Radio]="https://zeno.fm/radio/rocknroll-radio994c7517qs8uv/"
radio_stations[Trap Music]="https://zeno.fm/radio/trap-city-radio/"
