#!/usr/bin/env bash
# shellcheck disable=SC2034
# Defined variables, modify anything in quotes to your preferred software
DMENU="dmenu -i -l 20 -x 9 -y 9 -p"
# DMENU="rofi -dmenu -i -p"
DMBROWSER="firefox"
DMTERM="st -e"
DMEDITOR="emacsclient -c -a emacs"
PDF_VIEWER="zathura"
LOGOUT_LOCKER="slock"

# dm-setbg
setbg_dir="${HOME}/Pictures/wallpapers"
use_imv=0

# dm-maim
maim_dir="${HOME}/Pictures/Screenshots"
maim_file_prefix="maim"

# dm-confedit
declare -A confedit_list
confedit_list[confedit]="$HOME/scripts/dmenu/config/config"
confedit_list[alacritty]="$HOME/.config/alacritty/alacritty.org"
confedit_list[bash]="$HOME/.bashrc"
confedit_list[bash_profile]="$HOME/.bash_profile"
confedit_list[redshift]="$HOME/.config/redshift/redshift.org"
confedit_list[neofetch]="$HOME/.config/neofetch/config.conf"
confedit_list[doom emacs config.el]="$HOME/.config/doom/config.el"
confedit_list[doom emacs config.org]="$HOME/.config/doom/config.org"
confedit_list[doom emacs init.el]="$HOME/.config/doom/init.el"
confedit_list[doom emacs packages.el]="$HOME/.config/doom/packages.el"
confedit_list[dunst]="$HOME/.config/dunst/dunstrc.org"
confedit_list[bat]="$HOME/.config/bat/config"
confedit_list[fish]="$HOME/.config/fish/config.org"
confedit_list[picom]="$HOME/.config/picom/picom.conf"
confedit_list[ssh]="$HOME/.ssh/config"
confedit_list[xmobar]="$HOME/.config/xmobar/xmobarrc"
confedit_list[xmonad]="$HOME/.config/xmonad/xmonad.org"
confedit_list[xinitrc]="$HOME/.config/X11/xinitrc"
confedit_list[xresources]="$HOME/.config/X11/xresources"
confedit_list[nano]="$HOME/.config/nano/nanorc"
confedit_list[tmux]="$HOME/.config/tmux/tmux.org"
confedit_list[zathura]="$HOME/.config/zathura/zathurarc"
confedit_list[starship]="$HOME/.config/starship/starship.toml"
confedit_list[zsh]="$HOME/.config/zsh/.zshrc"
confedit_list[lf]="$HOME/.config/lf/lfrc"
confedit_list[zshenv]="$HOME/.zshenv"
confedit_list[zsh]="$HOME/.config/zsh/.zshrc"
confedit_list[aliases]="$HOME/.config/shell/aliases"
confedit_list[function]="$HOME/.config/shell/function"
confedit_list[zprofiel]="$HOME/.config/zsh/.zprofile"
confedit_list[lf]="$HOME/.config/lf/lfrc"
confedit_list[lf mappings]="$HOME/.config/lf/mappings"
confedit_list[lf settings]="$HOME/.config/lf/settings"
confedit_list[lf commands]="$HOME/.config/lf/commands"

# dm-confedit
declare -A radio_stations
radio_stations[50s Rewind]="https://zeno.fm/radio/50s-rewind/"
radio_stations[60s Rewind]="https://zeno.fm/radio/60s-rewind/"
radio_stations[70s Rewind]="https://zeno.fm/radio/70s-rewind/"
radio_stations[80s Rewind]="https://zeno.fm/radio/80s-rewind/"
radio_stations[90s Rock]="https://zeno.fm/radio/90s-rock/"
radio_stations[The 2000s]="https://zeno.fm/radio/the-2000s/"
radio_stations[Classical Radio]="https://zeno.fm/radio/classical-radio/"
radio_stations[Classical Relaxation]="https://zeno.fm/radio/radio-christmas-non-stop-classical/"
radio_stations[Classic Rock]="https://zeno.fm/radio/classic-rockdnb2sav8qs8uv/"
radio_stations[Gangsta49]="https://zeno.fm/radio/gangsta49/"
radio_stations[HipHop49]="https://zeno.fm/radio/hiphop49/"
radio_stations[Madhouse Country Radio]="https://zeno.fm/radio/madhouse-country-radio/"
radio_stations[PopMusic]="https://zeno.fm/radio/popmusic74vyurvmug0uv/"
radio_stations[PopStars]="https://zeno.fm/radio/popstars/"
radio_stations[RadioMetal]="https://zeno.fm/radio/radio-metal/"
radio_stations[RocknRoll Radio]="https://zeno.fm/radio/rocknroll-radio994c7517qs8uv/"
radio_stations[rb-hip-hop-163]="https://www.radio.es/genre/rap"

# This case statement lets you change what the DMENU variable is for different scripts
# Add more cases if necessary
# case "${0##*-}" in
    # "confedit") DMENU="dmenu -i -l 30 -p";;
# esac
