#!/usr/bin/env bash

# Exit if any command fails, if any undefined variable is used, or if a pipeline fails
set -euo pipefail

# Check if the configuration file exists, and if it does, source it
if [ -f "$HOME/scripts/dmenu/config/config" ]; then
  . "$HOME/scripts/dmenu/config/config"
else
  echo "configuration file not found" && exit 1
fi

connect_wifi() {
  bssid=$(nmcli device wifi list | sed -n '1!p' | cut -b 9- | ${DMENU} "Select Wifi  :" | cut -d' ' -f1)
  pass=$(yad --title="Connect to the Internet" --entry --entry-label="Password: " --hide-text)
  [ -n "$pass" ] && nmcli device wifi connect "$bssid" password "$pass" || nmcli device wifi connect "$bssid"
  sleep 10
  ping -q -c 2 -W 2 archlinux.org >/dev/null && notify-send "Network Manager" "has internet connection" || notify-send "Network Manager" "no internet connection"
}

disconnect_wifi() {
  bssid=$(nmcli device wifi list | sed -n '1!p' | cut -b 9- | ${DMENU} "Select Wifi  :" | cut -d' ' -f3)
  nmcli connection down "$bssid"
  sleep 2
  notify-send "has been disconnected $bssid"
}

main() {
  options=("Connect wifi" "Disconnect wifi")
  choice=$(printf '%s\n' "${options[@]}" | ${DMENU} 'Network option:' "${@}")
  case $choice in
    "Connect wifi") connect_wifi;;
    "Disconnect wifi") disconnect_wifi;;
  esac
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
