#!/usr/bin/env bash


set -euo pipefail
source "$HOME/scripts/dmenu/config/config"


chosen=$( grep -v "#" $HOME/scripts/dmenu/unicode | $DMENU "emojis:" ) || exit 1

    declare -a options=(
    "clipboard"
    "primary"
    )

select=$(printf "%s\n" "${options[@]}" | ${DMENU} 'Emojis: ' "${@}" ) || exit 1

    case $select in 
        'clipboard')
        copy=$(echo "$chosen" | sed "s/ .*//")
        echo "$copy" | tr -d '\n' | xclip -selection clipboard
        notify-send "'$copy' copied to clipboard." &
        ;;
        'primary')
        copy=$(echo "$chosen" | sed "s/.*; //" | awk '{print $1}')
        echo "$copy" | tr -d '\n' | xclip
        notify-send "'$copy' copied to primary." &
        ;;
        *)
        exit 0
        ;;
    esac


