#!/usr/bin/env bash
set -euo pipefail
source "$HOME/scripts/dmenu/config/config"


menu() {
  printf '%s\n' "Quit"
  printf '%s\n' "${!radio_stations[@]}" | sort
}

# Functions for sending notification messages
start_radio() {
  notify-send "Starting radio" "Playing station: $1. 🎶"
}

end_radio() {
  notify-send "Stopping radio" "You have quit dm-radio. 🎶"
}

main() {
  # Choosing a radio station from array sourced in 'config'.
  choice=$(menu | ${DMENU} 'Choose radio station:' "$@") || exit 1

  case $choice in
    Quit)
      end_radio ;
      pkill -f http
      exit
      ;;
    *)
      pkill -f http || echo "mpv not running."
      start_radio "$choice" ;
      mpv "${radio_stations["${choice}"]}"
      return
      ;;
  esac

}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
