#!/usr/bin/env bash


set -euo pipefail
source "$HOME/scripts/dmenu/config/config"

main() {
  # TODO: Fix cut line at some point
  bssid=$(nmcli device wifi list | sed -n '1!p' | cut -b 9- | ${DMENU} "Select Wifi  :" | cut -d' ' -f1)
  pass=$(echo "" | ${DMENU} "Enter Password  :")
  # We are disabling a shellcheck warning about using && and || as it doesn't apply here.
  # shellcheck disable=SC2015
  [ -n "$pass" ] && nmcli device wifi connect "$bssid" password "$pass" || nmcli device wifi connect "$bssid"
  sleep 10
  if ping -q -c 2 -W 2 google.com >/dev/null; then
    notify-send "Your internet is working :)"
  else
    notify-send "Your internet is not working :("
  fi
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
